# Generated by Django 4.1.3 on 2022-11-08 21:36

import django.core.validators
from django.db import migrations, models
import swimrecords.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SwimRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('team_name', models.CharField(max_length=100)),
                ('relay', models.BooleanField()),
                ('stroke', models.CharField(max_length=100, validators=[swimrecords.validators.validate_stroke])),
                ('distance', models.IntegerField(validators=[django.core.validators.MinValueValidator(50)])),
                ('record_date', models.DateTimeField(validators=[swimrecords.validators.validate_date])),
                ('record_broken_date', models.DateTimeField(validators=[swimrecords.validators.validate_new_record])),
            ],
        ),
    ]
